### ISSUE TITLE
retry section is confusing

### ISSUE THREAD

**Issue by mycroftcanner** [heckj/swiftui-notes#117]
I found the retry and trymap explanation super confusing.

**Comment by heckj** [comment]
thanks @mycroftcanner - let me tackle them individually and try out some variation text on you to see if that helps. You game?

(also - are you talking about the operator descriptions, or understanding one of the patterns? I'm assuming it's operator descriptions - the names linked under the "reference" chapter)

for tryMap - do you feel like you understand what the map operator does and how it does it? (my description of tryMap was very much predicated on understanding map)

for retry - do you feel like you get the "some operators can fail" and return a Failure type instead of any values? Is it the sequencing of what happens that is confusing - or more of how I describe what it's supposed to be doing?

**Comment by mycroftcanner** [comment]
> 1. the delay operator will delay further processing on the pipeline, in this case for a random selection of 1 to 5 seconds. By adding delay here in the pipeline, it will always occur, even if the original request is successful.

Here you should probably explain why you are adding a delay... actually it might be cool to implement an exponential backoff operator at some point.

> 2. retry is specified as trying 3 times. If you specify retry without any options, it will retry infinitely, and may cause your pipeline to never resolve any values or completions.

this is clear..

> 3. tryMap is being used to investigate errors after the retry so that retry will only re-attempt the request when the site didn’t respond.

I understand tryMap and Map... the part of the sentence I don't understand is how does the tryMap influences the retry.

**Comment by mycroftcanner** [comment]
@heckj 

> retry is specified as trying 3 times. If you specify retry without any options, it will retry infinitely, and may cause your pipeline to never resolve any values or completions.

I can't find anywhere in the official documentation that retry without count works.

**Comment by heckj** [comment]
Oooh - thank you @mycroftcanner !

The optional parameter has disappeared, and it now requires a value with with most recent value of  Combine, and I missed when that changed. I didn't have a specific unit test that worked a retry() operator without a value, which I found through experimentation in earlier.

I've updated that section of the reference documentation to not assert the retry has an optional value, since it's clearly now required. (A definite improvement IMO)

**Comment by heckj** [comment]
@mycroftcanner I've re-written the descriptive content around that sample, included in a pull request #123. I re-wrote it based on this thread, and hopefully it addresses your earlier questions more directly and completely. If you have any suggestions for further improvements here (or other call-outs where it's confusing), I'd love to have them.

I'll aim to merge in this change in another day or two after I've let the writing sit and re-read it myself for a review pass, after which it'll be updated on the public site - epub and pdf updates will be a little longer.

**Comment by mycroftcanner** [comment]
Thanks, I'll check it out in a bit...

It's kinda strange... retry doesn't seem to work at all. I have been trying to use it on a `Future<T, Error` and it never retries.

**Comment by heckj** [comment]
@mycroftcanner interesting - I'll see what I can dig up there too.. my test case uses URLSession.dataTaskPublisher, and I've verified that it definitely retries on that.

The *way* that it does the retry might be a tricky thing that you're hitting. My understanding (which means it's not guaranteed knowledge here) is that it re-does the subscription process through the chain that you've created. The debugging I used to verify how it's working is leveraging the `print()` operator, which might be a really good debugging tool for what you're seeing.

You can see an example of it and how I used it at https://github.com/heckj/swiftui-notes/blob/master/UsingCombineTests/RetryPublisherTests.swift#L91 or https://github.com/heckj/swiftui-notes/blob/master/UsingCombineTests/RetryPublisherTests.swift#L118

A variation of that test case with a Future() (instead of my Just() ) is what I'd look out to build an understanding of what's happening. The `print()` operator VERY helpfully details out all the major moving parts of Combine: subscription, receive, and request.

**Comment by mycroftcanner** [comment]
The retry operator used on the output of the following function doesn't do anything when the promise fails.

```
    func signin(cache: Authentication.Response? = nil) -> AnyPublisher<APIHandler, Error> {
        Future<APIHandler, Error> { promise in
            guard let cache = cache ?? self.cacheSubject.value else {
                promise(.failure(InstagramError.signInRequired))
                return
            }

            let handler = APIHandler()
            handler.authenticate(with: .cache(cache)) { result in
                switch result {
                case .failure(let error):
                    promise(.failure(error))
                default:
                    promise(.success(handler))
                }
            }
        }.eraseToAnyPublisher()
    }
```

**Comment by heckj** [comment]
I don't have your surrounding code to make a quick check of that, so I wrote an additional unit test into the stuff I've already got in place that works both Future and retry, with some interesting results.

The test itself can be found at https://github.com/heckj/swiftui-notes/blob/retry-update/UsingCombineTests/FuturePublisherTests.swift#L88-L133, and I went ahead and added in comments about what the `print()` operators generated as a means of explaining what's happening.

I won't repeat all that code here, but let me show you the core pipeline and the print output:

```
        let sut = Future<Bool, Error> { promise in
            print("invoking Future handler for resolving the provided promise")
            self.asyncAPICall(sabotage: true) { (grantedAccess, err) in
                print("invoking async completion handler to return a resolved promise")
                if let err = err {
                    promise(.failure(err))
                }
                promise(.success(grantedAccess))
            }
        }
        .print("before_retry:")
        .retry(2)
        .print("after_retry:")
```

and it's printed output:
```
        invoking Future handler for resolving the provided promise
        before_retry:: receive subscription: (Future)
        after_retry:: receive subscription: (Retry)
        after_retry:: request unlimited
        before_retry:: request unlimited
         * making async call (delay of 1 seconds)
        invoking async completion handler to return a resolved promise
        before_retry:: receive error: (anErrorExample)
        before_retry:: receive subscription: (Future)
        before_retry:: request unlimited
        before_retry:: receive error: (anErrorExample)
        before_retry:: receive subscription: (Future)
        before_retry:: request unlimited
        before_retry:: receive error: (anErrorExample)
        after_retry:: receive error: (anErrorExample)
        .sink() received the completion:  failure(UsingCombineTests.FuturePublisherTests.TestFailureCondition.anErrorExample)

```

From the above, you can see that it's definitely retrying the subscription - the lines `receive subscription: (Future)` show that happening, but the underlying call that is within the Future publisher isn't being re-done.

The Future publisher isn't something that we have access to see the source on, but from this output I'd guess that it's retaining it's state and is basically a "one-shot" publisher - meaning repeating the subscription (which is what `retry` does) won't re-trigger it. I don't have any internal insight here, and in fact I'd probably suggest that would be a good bug to file with Apple - it certainly seems (to me) like redoing the subscription should reset the Future's internal state and trigger it again.

(side note - in fact, I filed this with Apple, although I'd recommend you do the same - my feedback number, in case you want to reference it: FB7455914)

From the print statements to get an idea of sequencing of the callbacks, it looks like the Future's closure it invoked nearly immediately after it's created, not when it gets a subscription.

A possible workaround would be to recreate the future on each subscription. The only way I can think to do this explicitly (short of making your own Future like publisher) might be to wrap the Future publisher in flatMap, which basically generates a new Publisher object for every request that it gets.

**Comment by heckj** [comment]
(re that workaround - you can see some of that kind of pattern in the pattern section https://heckj.github.io/swiftui-notes/#patterns-sequencing-operations - which sequences a number of futures on one another, all within a pipeline)

**Comment by heckj** [comment]
@mycroftcanner I was continuing to poke around at this, and one option that looks fairly promising is to wrap a Future() publisher with Deferred(), which seems to be exactly what you're looking for - and I suspect would enable the use of things like the retry() operator.

I haven't yet done this in a unit test to show an example, but my Deferred example is anemic at best right now, so I'm going to put a little work into expanding that using Deferred to wrap Future to see if I can get that all operational with retry() to show it working. 

Given Deferred's description, I think it matches beautifully, but proof will be in the usage.
