### ISSUE TITLE
Catch example bug

### ISSUE THREAD

**Issue by mycroftcanner** [heckj/swiftui-notes#131]
Xcode can be really confusing at times:

```swift
let publisher = PassthroughSubject<String, Never>()

let x = publisher
    .flatMap { name in
        return Future<String, Error> { promise in
            promise(.success(name))
        }.catch { _ in
            Just("Caught")
        }.map { result in
            return "\(result) foo"
        }
}.sink { result in
    print(result)
}

publisher.send("boo")

```

If you change the above code to display an error using os_log or print(error) :

```swift
}.catch { error in
             os_log("%s", type: .error, error.localizedDescription, error)
            return Just("Caught")
        }
```

:psyduck:

Xcode will complain: 

>Cannot assign value of type 'AnyCancellable' to type 'AnyCancellable?’

Inside a playground the error becomes: 

>Cannot invoke 'sink' with an argument list of type '(@escaping (String) -> ())'

**Comment by heckj** [comment]
How interesting! It looks like the playground is providing a better error message - I'd guess (but not sure) due to the improved swift compiler diagnostic engine that was being integrating starting with swift 5.1

The core of this is that swift (and combine via swift) is really picky about optional vs. non-optional to match the type. The type of `AnyCancellable` is a very different critter than `AnyCancellable?` to the compiler, which causes the compiler to get cranky.

you'd think it would be easy to send a non-optional type into one that accepts an optional, but it isn't. I saw *exactly* the same kind of issue when using `.assign()`. You end up needing to make the type transformation somewhere in your code to use the alternate type. 

When I try the same in my sample code, I get a type inference issue, running afoul the compiler not being able to infer the type. You can find some additional detail at https://stackoverflow.com/questions/42213656/how-flatmap-api-contract-transforms-optional-input-to-non-optional-result/42213785#42213785

I'm afraid it's one of those fundamental issues in swift itself, and its being address in the compiler diagnostic engine, but we could always wish it was further along. If you happen to be a fan of podcasts, there was an interesting overview of that work at https://spec.fm/podcasts/swift-unwrapped/313353
