### ISSUE TITLE
Trying to solve a multi-subscriber issue

### ISSUE THREAD

**Issue by Dlemex** [heckj/swiftui-notes#191]
**Describe the solution you'd like**
I have a processing publisher which matches async requests and responses.  When a match occurs, it sends the match object.  When no more requests are pending, it generated an idle object to tell the subscriber that all their requests are finished.  All processing occurs in batches.  I have been using a PassthroughSubject with send().

Initially, I used an enum(match(result); idle) to report results and a global handler in the code which must keep track of whose requests are being processed and then notifying the requestor of matches and completion.  Also, as it is going into an SDK, I wanted to eliminate the enum and I wanted to add an audit subscriber that would log all processed matches.

I also realized that for the regular subscriber to that publisher, it would make more sense to just send matches and then report completion when the batch of requests finished.  Each creator of requests could subscribe and then when completion occurs, perform the appropriate logic locally.

I found no way to send completion, without permanently shutting down the PassthroughSubject even if a new subscriber connects.  

It seemed like multicasting is the answer as I want each match to be sent to the current request subscriber and to the audit subscriber.  I just cannot figure a way to send completion to the only the request subscription.

**Describe alternatives you've considered**

After giving up on the completion feature, I have, for now, used a nil match to indicate the end of the processing group and I made the auditor ignore nils. 

I really wanted to just the completion handler since it cleaned up the call site and would localize processing.  And using the completion feature, it would also support errors in the future.  I just cannot figure out a way to use it without creating a new top-level PassthroughSubject after every completion or publishing the match to two different subscribers.  But even then the completion shutting down the PassthroughSubject remains.

I guess a possible solution would be to create my own subject that kept track of the multicast subjects created and then send a completion only to the requestor subjects as appropriate.

I hope that I have just overlooked something in Combine.

**Comment by heckj** [comment]
:wave: @Dlemex  - 

For more general questions like this, I'd like to encourage you to leverage a site such as StackOverflow, as there will be FAR more people (and many of them quite a bit smarter than me) who will be looking and potentially able to answer it. That said, I'll do my best to at least give you take and advice - 

First off, Combine has a pretty strict interpretation of what a completion is and means - and yes, they terminate Combine pipelines for a subscriber when they're complete. It sounds like you're fighting what Combine is doing because you want a slightly different mechanism, and that's going to be tricky to deal with.

I'd recommend doing what you can to reframe your problem such that you *can* use the Combine as it is. I'm inferring that you want to have a more "interactive" RPC style thing based on the comment about processing, sending matches, and then wanting to do more at a later time. What you might consider as a possible alternative is a function or method (on a class, struct, or whatever) that returns a Publisher that sends does this sending of all found matches and terminates when it's done.

Then use the publisher pipeline, marking it completed, and letting that structure terminate when it's complete (which is what Combine wants to do by design) - and creating and using a new pipeline on the next request for matches.

Be aware that pipelines are relatively cheap (both memory and CPU processing wise) to create, so creating dozens of them in short order, and then destroying them just a bit later, isn't an issue. That's how they were built to be used, and in some respect - any time you use Combine's [flatMap](https://heckj.github.io/swiftui-notes/#reference-flatmap) operator, that's what is happening under the covers.

Multi-cast, by comparison, would come in handy if you had many different receivers of that match object and you wanted to constrain the generation of requests to a smaller number. A frequent use case in this regard is doing something with a web API, which is time consuming (at minimum) - so if you have say 4 different objects wanting the same answer, you can use multicast to make a single (expensive) request, get the response, and then propagate the answer back to the 4 different objects rather than having to make an individual request for each object.

**Comment by Dlemex** [comment]
Thanks for the reply and the suggestions.  I think your suggestion to return a publisher might be the solution for each match if the are inexpensive.  That moves the logic of "completeness" back to client.  Thanks again for your hard work.
