### ISSUE TITLE
Updated Error Message Attempting To Assign A Non-Optional Type To A Keypath That Expects Has An Optional Type

### ISSUE THREAD

**Issue by MaxMacleod** [heckj/swiftui-notes#221]
Please see https://heckj.github.io/swiftui-notes/#reference-assign

This states that:

`Type of expression is ambiguous without more context`

> This error can occur when you are attempting to assign a non-optional type to a keypath that expects has an optional type. For example, UIImageView.image is of type UIImage?, so attempting to assign an output type of UIImage from a previous operator would result in this error message.

However I believe that this error message has changed. With Xcode 11.7 it is:

`error: key path value type ‘Foo?' cannot be converted to contextual type ‘Foo'`

**Comment by heckj** [comment]
Ah, thank you Max! I'll double check Xcode, including the new 12 beta - not at all surprising that the error codes are getting better, with the swift compiler diagnostic system updates, so that's super-pleasant to see. I'll update it and keep a reference to the older message, in case someone hits it with an older version as well.

**Comment by MaxMacleod** [comment]
Great, happy to help! Really enjoying the book. The Patterns and Recipes section in particular is super useful.
